import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Head from "next/head";
import { Locale } from "@/i18n.config";

const inter = Raleway({
   weight: ["300", "400", "500", "600", '800'],
   subsets: ["latin"],
   style: ['normal'],
   display: 'swap',
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   params: { lang },
   children,
}: Readonly<{
   children: React.ReactNode;
   params: { lang: Locale }
}>) {
   return (
      <html lang="en">
         <Head>
            <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
            <meta name="apple-mobile-web-app-capable" content="yes" />
            <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
         </Head>
         <body className={inter.className}>
            <Header lang={lang} />
            <main className="pt-[0.5px]">
               {children}
            </main>
            <Footer />
         </body>
      </html>
   );
}
