name: deployment-production

on:
    push:
        branches: [ main, ci-cd ]

jobs:
    deployment-production:
        runs-on: ubuntu-latest
        steps:
            -   name: Check Out Repo
                uses: actions/checkout@v2

            -   name: Copy updated files
                uses: appleboy/scp-action@v0.1.3
                with:
                    password: ${{ secrets.SSH_PASSWORD }}
                    host: ${{ secrets.SSH_HOST_PROD }}
                    username: ${{ secrets.SSH_USER_PROD }}
                    source: ./
                    target: ~/../var/www/app

            -   name: Rebuild project
                uses: appleboy/ssh-action@master
                with:
                    password: ${{ secrets.SSH_PASSWORD }}
                    host: ${{ secrets.SSH_HOST_PROD }}
                    username: ${{ secrets.SSH_USER_PROD }}
                    port: 22
                    command_timeout: 60m
                    script: |
                        chown -R ${USER} .
                        docker compose --env-file /var/www/.env -f  ~/../var/www/app/docker-compose.yml up -d --build
                        docker image rm app_app app_api app_admin -f
                        # rm -rf /var/www/app/